services:
  gitea:
    container_name: ymmy-git
    image: gitea/gitea:1.24-rootless
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=sqlite3
      - GITEA__server__START_SSH_SERVER=false
      - GITEA__indexer__REPO_INDEXER_ENABLED=false
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1.0"
